name: Image Build and Push

on:
  push:
    branches:
      - main
    tags:
      - '*.*.*' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract version tag
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: username/app:${{ steps.extract_version.outputs.tag }}
